### ISSUE TITLE
$EMPTY

### ISSUE THREAD

**Issue by lazydune** [punchlemon/minishell#2]
# support $EMPTY
## example
the cmmand
```
$EMPTY echo hi
```
is recognized
```
echo hi
```
![incorrect image](https://github.com/user-attachments/assets/db19b397-7596-40b1-ad90-60b99c892b66)
![correct image](https://github.com/user-attachments/assets/146a51c0-9639-42bf-8629-573acb58f512)

**Comment by lazydune** [comment]
![image](https://github.com/user-attachments/assets/2ed544fc-e640-40b2-80f7-216c61224012)

**Comment by noburestaurant** [comment]
![image](https://github.com/user-attachments/assets/3a21e90d-f84b-4db0-a86a-62ff7320f83a)

**Comment by noburestaurant** [comment]
まだ$EMPTYが"\0"になってるっぽい

**Comment by lazydune** [comment]
I made pull request
#3
